# Data
train_path: /kaggle/working/Jewellery-Classification/dataset/training
test_path: /kaggle/working/Jewellery-Classification/dataset/test
val_path: None
num_classes: 5 # 2 Chest Xray dataset, 5 for Jewellery dataset
batch_size: 128
shuffle: True

# Parameters
num_epochs: 100
learning_rate: 0.01
momentum: 0.5
patience: 5
dropout: 0.3

# Model
model: vgg16 # vgg16, vgg19, resnet18 or resnet50
pretrained: True
freeze: False

save_path: ./save
