# Data
train_path: /kaggle/input/vietnamese-foods/Images/Train
test_path: /kaggle/input/vietnamese-foods/Images/Test
val_path: /kaggle/input/vietnamese-foods/Images/Validate
num_classes: 30 
batch_size: 128
shuffle: True

# Parameters
num_epochs: 100
learning_rate: 0.01
momentum: 0.5
patience: 5
dropout: 0.3

# Model
model: vgg19 # vgg16, vgg19, resnet18 or resnet50
pretrained: True
freeze: False

save_path: ./save
