# Data
train_path: /kaggle/input/chest-xray-pneumonia/chest_xray/train
test_path: /kaggle/input/chest-xray-pneumonia/chest_xray/test
val_path: /kaggle/input/chest-xray-pneumonia/chest_xray/val
num_classes: 2
batch_size: 128
shuffle: True

# Parameters
num_epochs: 100
learning_rate: 0.01
momentum: 0.5
patience: 5
dropout: 0.3

# Model
model: vgg16 # vgg16, vgg19, resnet18 or resnet50
pretrained: True
freeze: False

save_path: ./save
